/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MasterQuestion = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'subject' : IDL.Text,
  'solutionSteps' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'originalNumbers' : IDL.Vec(IDL.Text),
  'chapter' : IDL.Text,
});
export const Stats = IDL.Record({
  'totalQuestions' : IDL.Nat,
  'totalVariants' : IDL.Nat,
});
export const Variant = IDL.Record({
  'id' : IDL.Nat,
  'decimalMode' : IDL.Bool,
  'masterId' : IDL.Nat,
  'correctIndex' : IDL.Nat,
  'createdAt' : IDL.Int,
  'mcqOptions' : IDL.Vec(IDL.Text),
  'answer' : IDL.Text,
  'questionText' : IDL.Text,
  'fractionMode' : IDL.Bool,
});

export const idlService = IDL.Service({
  'createMasterQuestion' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createVariant' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Bool,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteMasterQuestion' : IDL.Func([IDL.Nat], [], []),
  'deleteVariant' : IDL.Func([IDL.Nat], [], []),
  'exportData' : IDL.Func([], [IDL.Text], ['query']),
  'getMasterQuestion' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(MasterQuestion)],
      ['query'],
    ),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getVariant' : IDL.Func([IDL.Nat], [IDL.Opt(Variant)], ['query']),
  'importData' : IDL.Func([IDL.Text], [], []),
  'listAllMasterQuestions' : IDL.Func([], [IDL.Vec(MasterQuestion)], ['query']),
  'listVariantsByMasterId' : IDL.Func([IDL.Nat], [IDL.Vec(Variant)], ['query']),
  'searchMasterQuestionsByChapter' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MasterQuestion)],
      ['query'],
    ),
  'searchMasterQuestionsBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MasterQuestion)],
      ['query'],
    ),
  'searchMasterQuestionsByTopic' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MasterQuestion)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MasterQuestion = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'subject' : IDL.Text,
    'solutionSteps' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'originalNumbers' : IDL.Vec(IDL.Text),
    'chapter' : IDL.Text,
  });
  const Stats = IDL.Record({
    'totalQuestions' : IDL.Nat,
    'totalVariants' : IDL.Nat,
  });
  const Variant = IDL.Record({
    'id' : IDL.Nat,
    'decimalMode' : IDL.Bool,
    'masterId' : IDL.Nat,
    'correctIndex' : IDL.Nat,
    'createdAt' : IDL.Int,
    'mcqOptions' : IDL.Vec(IDL.Text),
    'answer' : IDL.Text,
    'questionText' : IDL.Text,
    'fractionMode' : IDL.Bool,
  });
  
  return IDL.Service({
    'createMasterQuestion' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createVariant' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Bool,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteMasterQuestion' : IDL.Func([IDL.Nat], [], []),
    'deleteVariant' : IDL.Func([IDL.Nat], [], []),
    'exportData' : IDL.Func([], [IDL.Text], ['query']),
    'getMasterQuestion' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(MasterQuestion)],
        ['query'],
      ),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getVariant' : IDL.Func([IDL.Nat], [IDL.Opt(Variant)], ['query']),
    'importData' : IDL.Func([IDL.Text], [], []),
    'listAllMasterQuestions' : IDL.Func(
        [],
        [IDL.Vec(MasterQuestion)],
        ['query'],
      ),
    'listVariantsByMasterId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Variant)],
        ['query'],
      ),
    'searchMasterQuestionsByChapter' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MasterQuestion)],
        ['query'],
      ),
    'searchMasterQuestionsBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MasterQuestion)],
        ['query'],
      ),
    'searchMasterQuestionsByTopic' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MasterQuestion)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };