/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MasterQuestion {
  'id' : bigint,
  'topic' : string,
  'subject' : string,
  'solutionSteps' : Array<string>,
  'createdAt' : bigint,
  'text' : string,
  'originalNumbers' : Array<string>,
  'chapter' : string,
}
export interface Stats { 'totalQuestions' : bigint, 'totalVariants' : bigint }
export interface Variant {
  'id' : bigint,
  'decimalMode' : boolean,
  'masterId' : bigint,
  'correctIndex' : bigint,
  'createdAt' : bigint,
  'mcqOptions' : Array<string>,
  'answer' : string,
  'questionText' : string,
  'fractionMode' : boolean,
}
export interface _SERVICE {
  'createMasterQuestion' : ActorMethod<
    [string, string, string, string, Array<string>, Array<string>],
    bigint
  >,
  'createVariant' : ActorMethod<
    [bigint, string, string, Array<string>, bigint, boolean, boolean],
    bigint
  >,
  'deleteMasterQuestion' : ActorMethod<[bigint], undefined>,
  'deleteVariant' : ActorMethod<[bigint], undefined>,
  'exportData' : ActorMethod<[], string>,
  'getMasterQuestion' : ActorMethod<[bigint], [] | [MasterQuestion]>,
  'getStats' : ActorMethod<[], Stats>,
  'getVariant' : ActorMethod<[bigint], [] | [Variant]>,
  'importData' : ActorMethod<[string], undefined>,
  'listAllMasterQuestions' : ActorMethod<[], Array<MasterQuestion>>,
  'listVariantsByMasterId' : ActorMethod<[bigint], Array<Variant>>,
  'searchMasterQuestionsByChapter' : ActorMethod<
    [string],
    Array<MasterQuestion>
  >,
  'searchMasterQuestionsBySubject' : ActorMethod<
    [string],
    Array<MasterQuestion>
  >,
  'searchMasterQuestionsByTopic' : ActorMethod<[string], Array<MasterQuestion>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];